default_language_version:
  node: 16.0.0
repos:
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v2.1.0"
    hooks:
      - id: prettier
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: no-commit-to-branch
        args:
          - --branch
          - staging
          - --branch
          - main
