name: "Pre-Commit Check"

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - uses: pre-commit/action@v2.0.2
